In [3]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [4]:
yerevan_historical = pd.read_csv('../data/yerevan_historical_clean/sale_historical.csv')
yerevan_actual = pd.read_csv('../data/yerevan_actual_clean/sale_actual.csv')

## Modifying historical data columns

In [5]:
yerevan_historical.drop(columns=['sold_date', 'days_in'], inplace=True)

In [6]:
yerevan_actual['backup_status'] = 'not sold'

In [7]:
df = pd.concat([yerevan_historical, yerevan_actual], axis=0)

In [11]:
df[df['id']==10895]

,backup_status,id,price,rooms,square_meters,address,source,furniture,renovation,price_per_meter,...,height,bathroom,rent_or_sale,links,download_date,y,x,closest_metro,walking_distance_to_metro(m),district
79785,not sold,10895,125000.0,3.0,54.0,"Yerevan, Center, Tigran Mets Ave",real-estate.am,1.0,NaN,2314.814815,...,2.8,1.0,sale appartments,https://www.real-estate.am/en/2-bedrooms/apart...,2023-03-13 18:12:05,44.513112,40.166182,Zoravar Andranik,669,Kentron

In [9]:
df = df.drop_duplicates(subset=['id'], keep='last')
df = df.loc[~((df['backup_status'] == 'sold') & (df['id'].duplicated()))]

In [10]:
df = df.dropna(subset=['district']).reset_index(drop=True)

## Price change table

In [12]:
df1 = pd.concat([yerevan_historical, yerevan_actual], axis=0)

In [16]:
df1[df1['id']==10895]

,backup_status,id,price,rooms,square_meters,address,source,furniture,renovation,price_per_meter,...,height,bathroom,rent_or_sale,links,download_date,y,x,closest_metro,walking_distance_to_metro(m),district
79785,price change,10895,125000.0,3.0,54.0,"Yerevan, Center, Tigran Mets Ave",real-estate.am,1.0,NaN,2314.814815,...,2.8,1.0,sale appartments,https://www.real-estate.am/en/2-bedrooms/apart...,2023-03-13 18:12:05,44.513112,40.166182,Zoravar Andranik,669,Kentron

In [14]:
df1.loc[df1.duplicated(subset=['id'], keep=False), 'backup_status'] = 'price change'
df1 = df1.drop_duplicates(subset=['id'], keep='last')

In [15]:
df1 = df1.dropna(subset=['district']).reset_index(drop=True)

In [79]:
df_clean = df.dropna().reset_index(drop=True)

In [67]:
df.to_csv(r'../data/yerevan_combined_clean/sale_combined.csv', index=False)
df_clean.to_csv(r'../data/yerevan_combined_clean/sale_clean_combined.csv', index=False)
df1.to_csv(r'../data/yerevan_combined_clean/sale_combined_price_change.csv', index=False)